# https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md

debug = true

[registry."docker.io"]
  mirrors = ["mirrors.163.com","mirrors.tuna.tsinghua.edu.cn","mirrors.aliyun.com","dockerproxy.cn","https://docker.rainbond.cc"]
  http = false
